const path = require('path')
const fs = require('fs')

let data = fs.readFileSync(path.join(__dirname, './pubg-red.ont'), 'utf8').toString()
let out = data
    .replace(/<RX [0-9]+.[0-9]+.[0-9]+>/g, '')
    .replace(/<RX [0-9]+.[0-9]+.[0-9]+-[0-9]+>/g, '')
    .replace(/<RF>([^>]*)<Rf>/g, '')
    .replace(/<HE>([^>]*)<He>/g, '')
    .replace(/<TS>([^>]*)<Ts>/g, '')
    .replace(/<FI>/g, '<i>')
    .replace(/<Fi>/g, '</i>')
    .replace(/<FR>/g, '')
    .replace(/<Fr>/g, '')
    .replace(/  /g, ' ')
    .replace(/\–/g, '&ndash;')
    .replace(/\„/g, '&bdquo;')
    .replace(/\”/g, '&rdquo;')
    .replace(/<PS><i>/g, '<b>')
    .replace(/<\/i>[.]<Ps>/g, '.</b>')
    .replace(/<\/i>[:]<Ps>/g, ':</b>')
    .replace(/<\/i>, <i>/g, ', ')
    .replace(/<\/i>: <i>/g, ': ')

fs.writeFileSync('./pubg-text.ont', out, {encoding: 'utf-8'})
fs.writeFileSync('../../scripture/bmc/pubg-text.ont', out, {encoding: 'utf-8'})
